# Generated by Django 5.2.7 on 2026-01-30 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kursus', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelas',
            name='instruktur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kelas_set', to='kursus.instruktur'),
        ),
        migrations.CreateModel(
            name='Pendaftaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_daftar', models.DateTimeField(auto_now_add=True)),
                ('selesai', models.BooleanField(default=False)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendaftar', to='kursus.kelas')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendaftaran', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-tanggal_daftar'],
                'unique_together': {('siswa', 'kelas')},
            },
        ),
    ]
